root: results/signatures/breast

n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  cca:
  unintegrated:
  ldvae:
  harmony:
  scvi:
  bbknn:
  mnc:
  scalop:
  genenmf:

random_seeds: 5


scenarios:
  wu_breast:
    data_path: data/raw/Wu_breast.h5ad
    signatures:
      - wu_4
      - wu_6

#  chung_breast:
#    data_path: data/raw/Chung_breast.h5ad
#    signatures:
#      - wu_4
#      - wu_6

signatures:
  wu_4:
    annotation_path: annotations/wu_4.csv
    scoring_scenario: wu_breast
    n_cluster: 4
  wu_6:
    annotation_path: annotations/wu_6.csv
    scoring_scenario: wu_breast
    n_cluster: 6