root: results/gbm_subsample

methods:
  bbknn:
  harmony:
  genenmf:
  unintegrated:
  scvi:
  scalop:
  cca:

scenarios:
  neftel_smartseq2_brain:
    data_path: data/raw/Neftel_brain_SmartSeq2.h5ad
    n_samples:
      - 5
      - 10
      - 15
      - 20
    random_seeds: 10
    preprocessing:
      min_genes: 3000
      max_pct_mt: 20
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    signatures:
      - neftel_4
      - neftel_6




signatures:
  neftel_4:
    annotation_path: annotations/Neftel_4.csv
    scoring_scenario: neftel_smartseq2_brain
    n_cluster: 4

  neftel_6:
    annotation_path: annotations/Neftel_6.csv
    scoring_scenario: neftel_smartseq2_brain
    n_cluster: 6