root: results/signatures/debug


n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  cca:
  unintegrated:
  harmony:
  bbknn:
  mnc:
  scalop:


skip_preprocessing: True

random_seeds: 1

scenarios:
  neftel_0.0_0:
    data_path: results/signatures/gbm/data/preprocessed/neftel_smartseq2_brain.h5ad
    mem_scaling: 0.5
    signatures:
      - neftel_4

signatures:
  neftel_4:
    annotation_path: annotations/neftel_4.csv
    scoring_scenario: neftel_0.0_0
    n_cluster: 4

