root: results/signatures/gbm


n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  cca:
  unintegrated:
  ldvae:
  harmony:
  scvi:
  bbknn:
  mnc:
  scalop:
  genenmf:
  fastmnn:
  rpca:


random_seeds: 5

scenarios:
  neftel_smartseq2_brain:
    data_path: data/raw/Neftel_brain_SmartSeq2.h5ad
    preprocessing:
      min_genes: 3000
      max_pct_mt: 20
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    signatures:
      - neftel_4
      - neftel_6

  yuan_brain:
    data_path: data/raw/Yuan_brain.h5ad
    preprocessing:
      excluded_samples:
        - PJ016
        - PJ030
      min_genes: 700
      max_pct_mt: 20
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    signatures:
      - neftel_4
      - neftel_6

  couturier_brain:
    data_path: data/raw/Couturier_brain.h5ad
    preprocessing:
      excluded_samples:
        - BT368-GSC
        - BT397_2of2
        - BT364_2of2
        - BT368-GSC
        - BT363_2of2
        - BT363-GSC
      min_genes: 700
      max_pct_mt: 20
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    signatures:
      - neftel_4
      - neftel_6

  neftel_10x_brain:
    data_path: data/raw/Neftel_brain_10X.h5ad
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    preprocessing:
      excluded_samples:
        - "114"
    signatures:
      - neftel_4
      - neftel_6

  wang_brain:
    data_path: data/raw/Wang_brain.h5ad
    preprocessing:
      min_genes: 1000
      max_pct_mt: 5
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    signatures:
      - neftel_4
      - neftel_6

signatures:
  neftel_4:
    annotation_path: annotations/neftel_4.csv
    scoring_scenario: neftel_smartseq2_brain
    n_cluster: 4

  neftel_6:
    annotation_path: annotations/neftel_6.csv
    scoring_scenario: neftel_smartseq2_brain
    n_cluster: 6

