root: results/signatures/luad

n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  cca:
  unintegrated:
  ldvae:
  harmony:
  scvi:
  bbknn:
  mnc:
  scalop:
  genenmf:
  fastmnn:
  rpca:



random_seeds: 5


scenarios:
  kim_lung:
    data_path: data/raw/Kim_lung.h5ad
    signatures:
      - kim_3

  bischoff_lung:
    data_path: data/raw/Bischoff_lung.h5ad
    signatures:
      - kim_3

  laughney_lung:
    data_path: data/raw/Laughney_lung.h5ad
    signatures:
      - kim_3

signatures:
  kim_3:
    annotation_path: annotations/kim_3.csv
    scoring_scenario: kim_lung
    n_cluster: 3