root: results/signatures/scc

n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  cca:
  unintegrated:
  ldvae:
  harmony:
  scvi:
  bbknn:
  mnc:
  scalop:
  genenmf:


random_seeds: 5



scenarios:
  ji_skin:
    data_path: data/raw/Ji_skin.h5ad
    random_seeds: 5
    signatures:
      - ji_3

signatures:
  ji_3:
    annotation_path: annotations/ji_skin.csv
    scoring_scenario: ji_skin
    n_cluster: 3