root: results/signatures/sparse


n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  bbknn:
  unintegrated:

skip_preprocessing: True

random_seeds: 1

scenarios:
  neftel_smartseq2_0.0_0:
    data_path: data/sparse/neftel_0.0_0.h5ad
    mem_scaling: 0.01
    signatures:
      - neftel_4



signatures:
  neftel_4:
    annotation_path: annotations/neftel_4.csv
    scoring_scenario: neftel_smartseq2_0.0_0
    n_cluster: 4

