jobs: 100
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-.%j.err
    --account=account
    --ntasks=1
    --nodes=1
    --time={resources.runtime}
    --parsable
    {resources.slurm_extra}

default-resources:
    - mem_mb=3850
    - runtime=720
    - partition="compute"
    - slurm_extra=""

group-components:
  - signature_eval=20
  - overlap_eval=20
  - fast_integration=25