jobs: 100
executor: slurm

default-resources:
    - mem_mb=3850
    - runtime=360
    - partition="compute"
    - slurm_extra="--exclude compute-biomed-03,compute-biomed-09"

group-components:
  - preprocessing=10
  - signature_eval=10
  - overlap_eval=10
  - fast_integration=10