jobs: 100
executor: slurm

default-resources:
    - mem_mb=3850
    - runtime=720
    - partition="compute"
    - slurm_extra=""

group-components:
  - signature_eval=20
  - overlap_eval=20
  - fast_integration=5