jobs: 100
executor: slurm
default-resources:
    - mem_mb=3850
    - runtime=720
    - partition="compute"
    - slurm_extra=""

group-components:
  - signature_eval=50
  - overlap_eval=50
  - fast_integration=10