methods:
  bbknn: BBKNN
  harmony: Harmony
  harmony: Harmony
  mnc: MNC
  scvi: scVI
  genenmf: GeneNMF
  cca: CCA
  cnmf: cNMF
  unintegrated: Unintegr.
  scalop: scalop
  ldvae: "ldvae"
  combat: "Combat"
  scanorama: "Scanorama"
  dhaka: "Dhaka"
  rpca: rPCA


method_order: ['BBKNN', 'Harmony', 'scVI', 'MNC', 'ldvae', 'CCA', 'rPCA', 'Scanorama', 'Dhaka', 'Combat', "Unintegrated", "Unintegr.", "scalop", "GeneNMF"]

method_colormap:
  BBKNN: '#FF4433'        # Red
  Harmony: '#e18632'       # Orange  
  scVI: '#b59a32'          # Yellow-brown
  ldvae: '#8ba731'         # Yellow-green
  Scanorama: '#32b258'     # Green
  Dhaka: '#35ae95'         # Teal
  Combat: '#37abb2'        # Blue-green
  CCA: '#39a7d6'           # Light blue
  rPCA: '#1f77b4'          # Medium blue
  MNC: '#9467bd'           # Purple-violet
  Unintegrated: '#8f93f4'  # Purple-blue
  Unintegr.: '#8f93f4'     # Purple-blue (same as Unintegrated)
  scalop: '#db70f4'        # Bright purple
  GeneNMF: '#f667c6'       # Pink

method_markers:
  BBKNN: 'o'              # circle
  Harmony: 's'             # square
  scVI: '^'                # triangle up
  ldvae: 'v'               # triangle down
  Scanorama: 'D'           # diamond
  Dhaka: 'p'               # pentagon
  Combat: 'h'              # hexagon
  CCA: '*'                 # star
  rPCA: '+'                # plus
  MNC: 'x'                 # x
  Unintegrated: '<'        # triangle left
  Unintegr.: '<'           # triangle left (same as Unintegrated)
  scalop: '>'              # triangle right
  GeneNMF: 'd'             # thin diamond

datasets:
  kim_lung: "Kim"
  neftel_smartseq2_brain: "Neftel, SS2"
  neftel_10x_brain: "Neftel, 10X"
  wu_breast: "Wu"
  ji_skin: "Ji"
  vazquez_ovarian: "Vazques"
  bischoff_lung: "Bischoff"
  laughney_lung: "Laughney"
  couturier_brain: "Couturier"
  wang_brain: "Wang"
  yuan_brain: "Yuan"

font_config:
  axes.titlesize: 20
  axes.labelsize: 20
  legend.title_fontsize: 20
  legend.fontsize: 16
  xtick.labelsize: 16
  ytick.labelsize: 16
  svg.fonttype: 'none'
  font.family: 'sans-serif'
  font.sans-serif: ['Helvetica', 'Arial', 'Liberation Sans', 'DejaVu Sans']