root: results/scc

methods:
  bbknn:
  harmony:
  genenmf:
  unintegrated:
  scvi:
  scalop:
  cca:
  mnc:
  rpca:



scenarios:
  ji_skin:
    data_path: data/raw/Ji_skin.h5ad
    random_seeds: 5
    signatures:
      - ji_3

signatures:
  ji_3:
    annotation_path: annotations/ji_skin.csv
    scoring_scenario: ji_skin
    n_cluster: 3