root: results/integration/batch_key

plotting: False

n_hvgs:
  - "2000"

batch_key:
  - True
  - False

methods:
  cca:
  unintegrated:
  combat:
  ldvae:
  dhaka:
  harmony:
  scanorama:
  scvi:
  bbknn:
  mnc:
  rpca:
  fastmnn:


random_seeds: 5
n_samples: 
  - 0.8


scenarios:
  rms_all:
    data_path: data/raw/rms_all.h5ad
    mem_scaling: 3.0
    labels_path: labels/RMS.csv

  rms_scrna:
    data_path: data/raw/rms_scRNAseq.h5ad
    mem_scaling: 2.0
    labels_path: labels/RMS.csv

  rms_snrna:
    data_path: data/raw/rms_snRNAseq.h5ad
    mem_scaling: 2.0
    labels_path: labels/RMS.csv