root: results/integration/debug


n_hvgs:
  - "4000"

batch_key:
  - True

methods:
  unintegrated:
  combat:
  harmony:
  bbknn:

random_seeds: 1



scenarios:
  vazquez_ovarian:
    data_path: data/raw/vazquez_ovarian.h5ad
    labels_path: labels/vazquez_ovarian.csv
