root: results/integration/umap_rms

plotting: True
skip_preprocessing: True

n_hvgs:
  - "2000"

batch_key:
  - True

methods:
  unintegrated:
  harmony:
  scvi:
  bbknn:
  mnc:
  rpca:

random_seeds: 1


scenarios:
  rms_all:
    data_path: data/raw/rms_all.h5ad
    mem_scaling: 3.0
    labels_path: labels/RMS.csv

  rms_scrna:
    data_path: data/raw/rms_scRNAseq.h5ad
    mem_scaling: 2.0
    labels_path: labels/RMS.csv

  rms_snrna:
    data_path: data/raw/rms_snRNAseq.h5ad
    mem_scaling: 2.0
    labels_path: labels/RMS.csv